### PR TITLE
expo less gradient prototype

### PR DESCRIPTION
**Pull request by XantreGodlike**
I cannot launch the project
image
But I think this should work

### CODE REVIEW

**Comment by XantreGodlike** [comment]
@nandorojo

**Comment by XantreGodlike** [comment]
I think we can add explicit LinearGradient injection via react context

**Comment by nandorojo** [comment]
hey, i appreciate the PR but 1) i can't review it without it being tested, 2) i don't think metro supports try/catch requires, and 3) there's no need to tag me.

**Comment by XantreGodlike** [comment]
Ok will not to tag you, sorry. I think will be better dependency injection via react context

**Comment by XantreGodlike** [comment]
What do you think about it?
```tsx
<LinearGradientProvider value={LinearGradient}>
    <Skeleton />
</LinearGradientProvider>
```

**Comment by XantreGodlike** [comment]
And we can make some additional entry exports with binded `react-native-linear-gradient` and `expo-linear-gradient`

**Pull request closed without merging**
