### PR TITLE
update children TS type for MotiSkeleton

### PR DESCRIPTION
**Pull request by fobos531**
super simple change

`React.ReactChild` is a deprecated type, let's switch to `React.ReactNode`

### CODE REVIEW

**Comment by fobos531** [comment]
@nandorojo Let me know if any other changes are required on my end.

**Comment by nandorojo** [comment]
Let's use ReactElement for backwards compatibility since this is for one node

**Comment by fobos531** [comment]
@nandorojo Is there anything else required from my end here?

**Comment by nandorojo** [comment]
Merged!

**Pull request merged**
