### PR TITLE
Reanimated 2.3 + Improve Interactions Imports

### PR DESCRIPTION
**Pull request by nandorojo**
## What

Change `@motify/interactions` → `moti/interactions`

## Why

Currently, to use Moti Interactions, you have to install `@motify/interactions` separately. This is pretty annoying.

If you update `moti`, and forget to update `@motify/interactions`, then the babel plugin doesn't work properly, since `@motify/core` becomes a nested dependency.

This PR aims to greatly simplify the usage of Moti Interactions, by following the Next.js convention of imports like `next/link`.

## How

- Deprecate `@motify/interactions`. Instead, you only need to install `moti`, and import `moti/interactions`.
- Move `moti` to `expo-module-scripts`, rather than `react-native-builder-bob`. This made the `moti/interactions` simpler. The other packages still use Bob. TBD on if I'll change this. But I like using Expo tools here.

## Breaking Changes

`@motify/interactions` is deprecated. You need to uninstall this from your app.

If you're using Next.js, remove `@motify/interactions` from `next-transpile-modules`. 

Change all imports from `@motify/interactions` to `moti/interactions`:

```diff
- from '@motify/interactions'
+ from 'moti/interactions'
```

Your code editor will make this easy to do with a find-all-and-replace.

image

## TODO

- [x] Add deprecation warning to `@motify/interactions`
- [x] Edit docs
- [x] Add upgrade instructions to docs

## Install

To try this PR, you can install `moti@canary`

### CODE REVIEW

**Comment by nandorojo** [comment]
This is working well for me.

**Comment by 10000multiplier** [comment]
I'm getting this error with importing `moti/skeleton` when I try to run my app in the web browser:

```bash
./node_modules/moti/build/skeleton/skeleton.js 29:237
Module parse failed: Unexpected token (29:237)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
```

It works great on mobile.

**Comment by nandorojo** [comment]
you should open an issue. did you follow the web guide?

**Comment by 10000multiplier** [comment]
@nandorojo ah, of course I did not. Thanks!

**Pull request merged**
