### PR TITLE
Support `initial` & `custom` on `AnimatePresence`

### LINKED ISSUE #85: Using scale and rotate together sometimes ends up in an invisible component.
### What's happening?
Whenever you try to apply scale and rotate together the component sometimes renders and performs the animation, and sometimes it doesn't.

This is literally random as sometimes it works and sometimes it doesn't, I am not sure on how the library is implemented but might be some kind of race condition? I also include a video to show the problem plus the code to reproduce, it's literally me just pressing refresh many times.

https://user-images.githubusercontent.com/6232522/124679375-e04d9a00-de89-11eb-86d0-a8c7916345a5.mp4

### Code

```
import React from 'react';
import { View } from 'react-native';
import { MotiView } from 'moti';
import { registerRootComponent } from 'expo';

export function App(): JSX.Element {
    return (
        <View>
            <MotiView
                style={{ backgroundColor: 'blue', height: 300, width: 300 }}
                from={{ opacity: 0, scale: 0, rotate: '0deg' }}
                animate={{ opacity: 1, scale: 1, rotate: '45deg' }}
            />
        </View>
    );
}

export default registerRootComponent(App);
```

If you have an idea on why this is going on but don't have the time to fix it a brief explanation would be nice and I can make a pull request.

### Snack

https://snack.expo.io/@brandonma/moti-rotate-scale-bug

### PR DESCRIPTION
**Pull request by nandorojo**
closes #85, #83, #76, #65, #91, #55

Fixes transform issues.

Add `custom` and `initial` support for `AnimatePresence`.

Try it on canary:

```sh
yarn add moti@presence
```

## Example

```tsx
const ImageGallery = ({ direction, uri }) => {

  return (
    <AnimatePresence initial={false} custom={direction}>
      {visible && (
        <MotiImage
          exit={(custom) => {
            'worklet'

            return {
              translateX: custom === 1 ? -10 : 10
            }
          }}
          from={{ translateX: -10 }}
          animate={{ translateX: 0 }}
          source={{ uri }}
          key={uri}
        />
      )}
    </AnimatePresence>
  )
}
```

### CODE REVIEW

**Comment by nandorojo** [comment]
closes #85, #83, #76, #65

**Comment by nandorojo** [comment]
Released at version `0.12.0`

```sh
yarn add moti
```

**Comment by Stevemoretz** [comment]
Awesome! Thank you so much! 
Can't find the relevant docs unfortunately, what is the custom key for is it the replacement for animate key?

**Comment by nandorojo** [comment]
The `custom` key is a feature of AnimatePresence from Framee Motion. You probably won’t use it (it’s rare), but we support it now.

The other prop is `initial`, which lets you disable the initial animation for a component in animate presence. Both of these are documented by framer motion.

**Comment by Stevemoretz** [comment]
> closes #85, #83, #76, #65, #91, #55
> 
> Fixes transform issues.
> 
> Add `custom` and `initial` support for `AnimatePresence`.
> 
> Try it on canary:
> 
> ```shell
> yarn add moti@presence
> ```
> 
> ## Example
> ```tsx
> const ImageGallery = ({ direction, uri }) => {
> 
>   return (
>     <AnimatePresence initial={false} custom={direction}>
>       {visible && (
>         <MotiImage
>           exit={(custom) => {
>             'worklet'
> 
>             return {
>               translateX: custom === 1 ? -10 : 10
>             }
>           }}
>           from={{ translateX: -10 }}
>           animate={{ translateX: 0 }}
>           source={{ uri }}
>           key={uri}
>         />
>       )}
>     </AnimatePresence>
>   )
> }
> ```
 Thank you so much for the response.
What is the direction in this example would you mind showing the part you're using this component so we can see what the direction is.

What about the transforms which are used without animation presence are those supported too?

I see you can passed a worklet to the exit can a worklet be used for animate as well?That's the way we can set the transforms right?

**Comment by nandorojo** [comment]
This will answer your questions: https://codesandbox.io/embed/framer-motion-image-gallery-pqvx3?codemirror=1

Direction is the direction of an image gallery you’re going.

as for the worklet, it’s only there because exit is a function, and all functions passed to moti need to be worklets. 

Transforms without animate presence are also all fixed in this release.

**Comment by kevingjs** [comment]
Currently I have a `MotiView` component with `from`, `animate` and `exit` props, I need to use `custom` prop from `AnimatePresence` in `from` and `exit` prop of `MotiView` child, the problem is that the function passed to `from` prop doesn't work.

```JavaScript
<MotiView
    from = {(step) => {
        'worklet'
        console.log("test");
        return { translateX: step < currentStep ? width : -width };
    }}
    animate = {{
        translateX: 0
    }}
    exit = {(step) => {
        'worklet'
        return { translateX: step < currentStep ? width : -width };
    }}
    transition = {{
        type: 'timing',
        duration: 300,
        easing: Easing.out(Easing.ease)
    }}
></MotiView>
```

The function in `from` prop just doesn't execute, why?

**Pull request merged**
