### PR TITLE
docs: added a note to use Chrome for StackBlitz examples

### PR DESCRIPTION
**Pull request by efstathiosntonas**
as per StackBlitz api, only Chrome is fully supported

### CODE REVIEW

**Review by nandorojo — COMMENTED** [review]
Probably better to put a note on each example page

**Comment by efstathiosntonas** [comment]
ok, what should be the message? Add it on top of every page?

**Comment by nandorojo** [comment]
780C65E5-7ED4-45F0-9E65-B039231BB11C

looks like this isn’t needed. it does work with firefox, and stackblitz warns for browsers that don’t

**Comment by nandorojo** [comment]
Although your original screenshot wasn’t very clear from them. Let’s add this on each example page:

If the example below doesn’t show properly, please try opening it on Chrome.

**Comment by efstathiosntonas** [comment]
@nandorojo I was using the developer edition of firefox, which one you used? That's weird.

Tomorrow I'll fix the docs

**Pull request merged**
